"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-id%a&_k1*&^+r6^8x$fbix3^d^9vd*5d77@!t!8v**6l1wi(f('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'django.contrib.sites',

    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',


    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # For social authentication
    'allauth.socialaccount.providers.keycloak',
    'blog.engine'
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'blog.engine.authentication.CookieAuthenticationWithExternalJWT',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    )
}

SOCIALACCOUNT_LOGIN_ON_GET = True


REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'TOKEN',
    'JWT_AUTH_REFRESH_COOKIE': 'TOKEN_REFRESH',
}
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIAL_AUTH_KEYCLOAK_CLIENT_ID = 'cvatClient'
SOCIAL_AUTH_KEYCLOAK_CLIENT_SECRET = 'gLnOEizuEf5l4IYGfAjnLLc3EKlcqdyH'
SOCIALACCOUNT_PROVIDERS = {
    'keycloak': {
        'APP': {
            'client_id': SOCIAL_AUTH_KEYCLOAK_CLIENT_ID,
            'secret': SOCIAL_AUTH_KEYCLOAK_CLIENT_SECRET,
            'key': ''
        },
        'KEYCLOAK_URL': 'http://10.24.65.226:7070',
        'KEYCLOAK_REALM': 'master'
    },
}

KEYCLOAK_CALLBACK_URL = 'http://localhost:8000/auth/callback'
SOCIAL_APP_LOGIN_REDIRECT_URL = 'http://localhost:8000/home'

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
